### PR TITLE
Add support for residential ward house listing packets

### PR DESCRIPTION
**Pull request by p-doyle**
These are the packets sent when viewing a ward in the residential district menu.  Unfortunately I do not have a way to test the struct but it should build at least...  I have tested an equivalent struct in python and nodejs though.  Also I wasn't sure how to handle the houseSize byte because it's also needed for the housePrice uint32... 

This is my first attempt at this, please be gentle!

### CODE REVIEW

**Comment by collett8192** [comment]
looks like [this one](https://github.com/SapphireServer/Sapphire/blob/develop/src/common/Network/PacketDef/Zone/ServerZoneDef.h#L2010)?

**Comment by p-doyle** [comment]
Ugh sorry, I swear I looked for an existing one but not hard enough apparently...  

Is it worth updating the PR to just update the IPC code for HousingWardInfo?  Or just close the PR and slink away in shame?

**Comment by collett8192** [comment]
Probably not updating it atm. Current code still targeting 5.35 hotfix and this packet is used in the code.

**Comment by NotAdam** [comment]
> Is it worth updating the PR to just update the IPC code for HousingWardInfo?

yes, feel free

**Pull request closed without merging**
