### PR TITLE
Social implementation

### PR DESCRIPTION
**Pull request by takhlaq**

### CODE REVIEW

**Comment by NotAdam** [comment]
shouldn't this be merged into develop instead?

**Comment by takhlaq** [comment]
it should be social_implementation

**Comment by SapphireMordred** [comment]
Erm... maybe a bit late... can this actually be merged??

**Comment by goaaats** [comment]
Not atm, I will port my personal changes to develop after housing is merged and PR to demo, even though they still need work - party and friends are both only semi-functional.

**Comment by takhlaq** [comment]
will reopen when its ready for review

**Pull request closed without merging**
