### PR TITLE
Various fixes, gear set unlocking and added ability to unlock mounts / orchestrion rolls

### PR DESCRIPTION
**Pull request by Skyliegirl33**
The `EquippedMannequin` db field is now used to determine how many gear sets are allowed to the character - this will have to be shared with the current gear set's index once I make a PR for that. Some actor controls were incorrect and missing, and two additional structs are now added. Other than that, there's just some new getters and setters for things I felt were missing, and some methods have an optional argument to not send update packets immediately since some functions shouldn't have that. `insertClassIntoDb` is also not hardcoded to level 1 anymore.

### CODE REVIEW

**Comment by Skyliegirl33** [comment]
Oops. Orchestrion item doesn't work right, so ignore that for now. I deleted it

**Comment by collett8192** [comment]
If you don't mind I'd like to take part of this PR and combine them into a later batch of 5.58 updates.

**Comment by Skyliegirl33** [comment]
I don't mind if you keep me as the commit author or mention it somewhere at least

**Comment by collett8192** [comment]
Sure thing, as in my every "stealed" commit.

**Comment by collett8192** [comment]
Here we go https://github.com/SapphireServer/Sapphire/pull/876/commits/ea27ff3a55c29ecdeddbe41215c7ecde0207d531
Messed up the commits in the first try which left multiple mentions above.

**Comment by Skyliegirl33** [comment]
Looks good!

**Pull request closed without merging**
