### PR TITLE
Update opcodes for 5.58 hotfix and fix CFCommenceHandler

### PR DESCRIPTION
**Pull request by Skyliegirl33**
This should fix the Duty Finder and update the opcodes for the newest client.

The opcode updates are courtesy of collett, Flavien Normand and Taezen.
I had assistance with CFCommenceHandler from Mordred and collett.

### CODE REVIEW

**Comment by NotAdam** [comment]
can you fix the extra whitespace that was added, likely by an autoformatter?

also not sure if you care, but your git email is set incorrectly

**Comment by Skyliegirl33** [comment]
That should have removed the whitepaces. Also, is it? My email is private, but I thought it would use the GH provided noreply email.

**Comment by NotAdam** [comment]
it was using `From: Skyliegirl33 <{ID}+{username}@users.noreply.github.com>` ;)

**Comment by Skyliegirl33** [comment]
Ahh, haha. I'll fix that

**Pull request merged**
